import type { Receipt } from '@/types';
import { requireSupabase } from '@/services/supabase';
const MAX_FILE_SIZE = 10 * 1024 * 1024;
const ALLOWED_TYPES = ['application/pdf', 'image/png', 'image/jpeg'];
export async function getReceipts(movementId: string): Promise<Receipt[]> { const { data, error } = await requireSupabase().from('comprobantes').select('*').eq('movimiento_id', movementId).order('created_at', { ascending: false }); if (error) throw error; return data; }
export async function uploadReceipt(movementId: string, file: File): Promise<Receipt> { if (file.size > MAX_FILE_SIZE) throw new Error('El archivo supera el límite de 10 MB.'); if (!ALLOWED_TYPES.includes(file.type)) throw new Error('Formato no permitido. Usá PDF, PNG o JPG.'); const path = `${movementId}/${crypto.randomUUID()}-${file.name}`; const client = requireSupabase(); const { error: uploadError } = await client.storage.from('comprobantes').upload(path, file, { contentType: file.type, upsert: false }); if (uploadError) throw uploadError; const { data: publicData } = client.storage.from('comprobantes').getPublicUrl(path); const { data, error } = await client.from('comprobantes').insert({ movimiento_id: movementId, nombre: file.name, tipo: file.type, url: publicData.publicUrl, size: file.size }).select().single(); if (error) { await client.storage.from('comprobantes').remove([path]); throw error; } return data;
}
export async function deleteReceipt(receipt: Receipt): Promise<void> { const client = requireSupabase(); const marker = '/comprobantes/'; const path = receipt.url.includes(marker) ? receipt.url.split(marker)[1] : ''; if (path) await client.storage.from('comprobantes').remove([path]); const { error } = await client.from('comprobantes').delete().eq('id', receipt.id); if (error) throw error; }
export async function getEventDocumentStats(eventId: string): Promise<{ loaded: number; total: number }> { const client = requireSupabase(); const { data: movements, error: movementError } = await client.from('movimientos').select('id').eq('evento_id', eventId); if (movementError) throw movementError; const ids = (movements as Array<{ id: string }>).map((movement) => movement.id); if (!ids.length) return { loaded: 0, total: 0 }; const { data, error } = await client.from('comprobantes').select('movimiento_id').in('movimiento_id', ids); if (error) throw error; return { loaded: (data as Array<{ movimiento_id: string }>).length, total: ids.length }; }
export const formatFileSize = (size: number) => size < 1024 * 1024 ? `${Math.ceil(size / 1024)} KB` : `${(size / (1024 * 1024)).toFixed(2)} MB`;
