import { ArrowUpRight, CalendarDays, ChevronRight, CircleDollarSign, TrendingDown, TrendingUp } from 'lucide-react';
import { motion } from 'framer-motion';
import { Container, Card, StatCard, Badge, Button, Section, Table, PageHeader, Skeleton, EmptyState } from '@/components/ui';
import { useDashboard } from '@/hooks/useDashboard';
import { formatCurrency, formatDate, formatError } from '@/utils/format';
import { sports, type Sport } from '@/types';
import { CURRENT_USER } from '@/config/user';
import { useDocumentStats } from '@/hooks/useReports';

const sportColors: Record<Sport, string> = { 'Básquet': 'bg-sky-500', 'Vóley': 'bg-violet-500', 'Patín': 'bg-pink-500', Hockey: 'bg-emerald-500' };

export function DashboardPage() {
  const { data, isLoading, isError, error } = useDashboard();
  const { data: documents } = useDocumentStats();
  if (isError) return <Container><PageHeader eyebrow="Resumen general" title={`Hola, ${CURRENT_USER.name} 👋`} description="Acá tenés una vista general de la actividad de Deportes Federados." /><EmptyState title="No se pudo cargar el resumen" description={formatError(error)} /></Container>;
  const income = data?.incomeTotal ?? 0;
  const expense = data?.expenseTotal ?? 0;
  const balance = income - expense;
  return <Container><PageHeader eyebrow="Resumen general" title={`Hola, ${CURRENT_USER.name} 👋`} description="Acá tenés una vista general de la actividad de Deportes Federados." action={<Button variant="secondary"><CalendarDays className="size-4" />Este mes <ChevronRight className="size-4" /></Button>} />
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .35 }}>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{isLoading ? [1, 2, 3, 4].map((item) => <Skeleton key={item} className="h-[142px] rounded-2xl" />) : <><StatCard label="Ingresos Totales" value={formatCurrency(income)} change="Datos reales" /><StatCard label="Gastos Totales" value={formatCurrency(expense)} change="Datos reales" positive={false} /><StatCard label="Balance General" value={formatCurrency(balance)} change="Datos reales" /><StatCard label="Eventos activos" value={String(data?.eventsCount ?? 0)} change="Total registrado" /></>}</div>
      <section className="mt-10"><div className="mb-4 flex items-end justify-between"><div><h2 className="display-font text-lg font-bold text-ink">Rendimiento por deporte</h2><p className="mt-1 text-sm text-slate-500">Ingresos acumulados del período seleccionado.</p></div><Button variant="ghost" className="hidden sm:inline-flex">Ver detalle <ArrowUpRight className="size-4" /></Button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{sports.map((sport, index) => { const amount = data?.bySport[sport] ?? 0; return <motion.div key={sport} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .06 }}><Card className="p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2.5"><span className={`size-2.5 rounded-full ${sportColors[sport]}`} /><span className="text-sm font-semibold text-slate-700">{sport}</span></div><span className="flex items-center gap-1 text-xs font-bold text-emerald-600"><TrendingUp className="size-3.5" />Ingresos</span></div><p className="mt-5 display-font text-xl font-extrabold text-ink">{formatCurrency(amount)}</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${sportColors[sport]}`} style={{ width: `${income ? Math.max(4, Math.min(100, amount / income * 100)) : 4}%` }} /></div></Card></motion.div>; })}</div></section>
      <section className="mt-10"><Section title="Últimos Eventos" action={<Button variant="ghost">Ver todos <ArrowUpRight className="size-4" /></Button>}>{isLoading ? <Skeleton className="h-48 rounded-2xl" /> : !data?.recentEvents.length ? <EmptyState title="Todavía no hay eventos" description="Los eventos creados aparecerán en este resumen." /> : <Card><Table><thead className="border-b border-slate-100 bg-slate-50/70 text-xs uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3.5 font-semibold">Evento</th><th className="px-5 py-3.5 font-semibold">Deporte</th><th className="px-5 py-3.5 font-semibold">Fecha</th><th className="px-5 py-3.5 font-semibold">Estado</th><th className="px-5 py-3.5 text-right font-semibold">Importe</th></tr></thead><tbody className="divide-y divide-slate-100">{data.recentEvents.map((event) => <tr key={event.id} className="transition hover:bg-slate-50/70"><td className="px-5 py-4 font-semibold text-slate-700">{event.nombre}</td><td className="px-5 py-4 text-slate-500">{event.deporte}</td><td className="px-5 py-4 text-slate-500">{formatDate(event.fecha)}</td><td className="px-5 py-4"><Badge tone={event.estado === 'Rendido' ? 'success' : event.estado === 'Finalizado' ? 'neutral' : 'warning'}>{event.estado}</Badge></td><td className="px-5 py-4 text-right font-semibold text-slate-700">—</td></tr>)}</tbody></Table></Card>}</Section></section>
      <div className="mt-8 grid gap-4 md:grid-cols-4"><Card className="flex items-center gap-4 bg-brand-600 p-5 text-white"><div className="rounded-xl bg-white/15 p-3"><CircleDollarSign className="size-6" /></div><div><p className="text-sm font-semibold text-brand-100">Balance del período</p><p className="mt-1 display-font text-2xl font-extrabold">{formatCurrency(balance)}</p></div><TrendingUp className="ml-auto size-5 text-brand-200" /></Card><Card className="flex items-center gap-4 p-5"><div className="rounded-xl bg-rose-50 p-3 text-rose-600"><TrendingDown className="size-6" /></div><div><p className="text-sm font-semibold text-slate-500">Gastos registrados</p><p className="mt-1 display-font text-2xl font-extrabold text-ink">{formatCurrency(expense)}</p></div><span className="ml-auto text-xs font-medium text-slate-400">datos reales</span></Card><Card className="flex items-center gap-4 p-5"><div className="rounded-xl bg-brand-50 p-3 text-brand-600"><CircleDollarSign className="size-6" /></div><div><p className="text-sm font-semibold text-slate-500">Movimientos</p><p className="mt-1 display-font text-2xl font-extrabold text-ink">{data?.movementsCount ?? 0}</p></div><span className="ml-auto text-xs font-medium text-slate-400">registrados</span></Card><Card className="flex items-center gap-4 p-5"><div className="rounded-xl bg-brand-50 p-3 text-brand-600"><CircleDollarSign className="size-6" /></div><div><p className="text-sm font-semibold text-slate-500">Comprobantes</p><p className="mt-1 display-font text-2xl font-extrabold text-ink">{documents?.loaded ?? 0} / {documents?.total ?? 0}</p></div><span className="ml-auto text-xs font-medium text-slate-400">cargados</span></Card></div>
    </motion.div></Container>;
}
