import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { Button, LoadingButton, Select } from '@/components/ui';
import { Field, controlClass } from '@/components/forms';
import { eventStatuses, sports, type Event } from '@/types';
import type { EventInput } from '@/services/events.service';
const schema = z.object({ fecha: z.string().min(1, 'Ingresá una fecha.'), deporte: z.enum(['Básquet', 'Vóley', 'Patín', 'Hockey']), nombre: z.string().trim().min(2, 'Ingresá un nombre.'), estado: z.enum(['Planificado', 'En curso', 'Finalizado', 'Rendido']), observaciones: z.string().optional() });
type FormValues = z.infer<typeof schema>;
export function EventForm({ event, onSubmit, onCancel, loading }: { event?: Event; onSubmit: (input: EventInput) => void; onCancel: () => void; loading: boolean }) { const { register, handleSubmit, formState: { errors } } = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { fecha: event?.fecha ?? new Date().toISOString().slice(0, 10), deporte: event?.deporte ?? 'Básquet', nombre: event?.nombre ?? '', estado: event?.estado ?? 'Planificado', observaciones: event?.observaciones ?? '' } }); return <form className="space-y-5" onSubmit={handleSubmit((values) => onSubmit({ ...values, observaciones: values.observaciones ?? '' }))}><Field label="Nombre del evento" error={errors.nombre?.message}><input className={controlClass} placeholder="Ej. Torneo Apertura" {...register('nombre')} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Fecha" error={errors.fecha?.message}><input type="date" className={controlClass} {...register('fecha')} /></Field><Field label="Deporte" error={errors.deporte?.message}><Select {...register('deporte')}>{sports.map((sport) => <option key={sport}>{sport}</option>)}</Select></Field></div><Field label="Estado" error={errors.estado?.message}><Select {...register('estado')}>{eventStatuses.map((status) => <option key={status}>{status}</option>)}</Select></Field><Field label="Observaciones" error={errors.observaciones?.message}><textarea rows={3} className={controlClass} placeholder="Notas generales de la rendición" {...register('observaciones')} /></Field><div className="flex justify-end gap-3 pt-2"><Button type="button" variant="secondary" onClick={onCancel}>Cancelar</Button><LoadingButton type="submit" loading={loading}>{event ? 'Guardar cambios' : 'Crear evento'}</LoadingButton></div></form>; }
