import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { Button, LoadingButton, Select } from '@/components/ui';
import { Field, controlClass } from '@/components/forms';
import { expenseCategories, incomeCategories, type Movement } from '@/types';
import { CURRENT_USER } from '@/config/user';
import { ReceiptManager } from '@/components/ReceiptManager';
import type { MovementInput } from '@/services/movements.service';
const schema = z.object({ fecha: z.string().min(1, 'Ingresá una fecha.'), categoria: z.string().min(1, 'Elegí una categoría.'), concepto: z.string().trim().min(2, 'Ingresá un concepto.'), importe: z.coerce.number().positive('El importe debe ser mayor a cero.'), observaciones: z.string().optional(), usuario: z.string().trim().min(2, 'Ingresá el usuario.') });
type FormValues = z.infer<typeof schema>;
export function MovementForm({ eventId, type, movement, disabled = false, onSubmit, onCancel, loading }: { eventId: string; type: 'Ingreso' | 'Gasto'; movement?: Movement; disabled?: boolean; onSubmit: (input: MovementInput) => void; onCancel: () => void; loading: boolean }) { const categories = type === 'Gasto' ? expenseCategories : incomeCategories; const { register, handleSubmit, formState: { errors } } = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { fecha: movement?.fecha ?? new Date().toISOString().slice(0, 10), categoria: movement?.categoria ?? categories[0], concepto: movement?.concepto ?? '', importe: movement?.importe, observaciones: movement?.observaciones ?? '', usuario: movement?.usuario ?? CURRENT_USER.name } }); return <form className="space-y-5" onSubmit={handleSubmit((values) => onSubmit({ ...values, tipo: type, evento_id: eventId, observaciones: values.observaciones ?? '' }))}><div className="grid gap-4 sm:grid-cols-2"><Field label="Fecha" error={errors.fecha?.message}><input disabled={disabled} type="date" className={controlClass} {...register('fecha')} /></Field><Field label="Categoría" error={errors.categoria?.message}><Select disabled={disabled} {...register('categoria')}>{categories.map((item) => <option key={item}>{item}</option>)}</Select></Field></div><Field label="Concepto" error={errors.concepto?.message}><input disabled={disabled} className={controlClass} placeholder="Ej. Venta de entradas" {...register('concepto')} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Importe" error={errors.importe?.message}><input disabled={disabled} type="number" step="0.01" min="0" className={controlClass} placeholder="0,00" {...register('importe')} /></Field><Field label="Usuario" error={errors.usuario?.message}><input disabled={disabled} className={controlClass} {...register('usuario')} /></Field></div><Field label="Observaciones" error={errors.observaciones?.message}><textarea disabled={disabled} rows={3} className={controlClass} placeholder="Opcional" {...register('observaciones')} /></Field>{movement && <ReceiptManager movementId={movement.id} disabled={disabled} />}<div className="flex justify-end gap-3 pt-2"><Button type="button" variant="secondary" onClick={onCancel}>Cerrar</Button>{!disabled && <LoadingButton type="submit" loading={loading}>Guardar cambios</LoadingButton>}</div></form>; }
