import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode, SelectHTMLAttributes } from 'react';
import { cn } from '@/utils/cn';
import { Inbox, Search, ChevronDown, X, CheckCircle2, AlertCircle, LoaderCircle } from 'lucide-react';

export function Container({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn('mx-auto w-full max-w-[1440px] px-4 sm:px-6 lg:px-8', className)}>{children}</div>; }
export function Button({ children, variant = 'primary', className, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'ghost' }) { return <button className={cn('inline-flex items-center justify-center gap-2 rounded-lg px-3.5 py-2 text-sm font-semibold transition focus:outline-none focus:ring-2 focus:ring-brand-200 disabled:opacity-50', variant === 'primary' && 'bg-brand-600 text-white shadow-sm hover:bg-brand-700', variant === 'secondary' && 'border border-slate-200 bg-white text-slate-700 hover:bg-slate-50', variant === 'ghost' && 'text-slate-500 hover:bg-slate-100 hover:text-slate-800', className)} {...props}>{children}</button>; }
export function Card({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn('rounded-2xl border border-slate-200/80 bg-white shadow-soft', className)}>{children}</div>; }
export function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'success' | 'warning' }) { return <span className={cn('inline-flex rounded-full px-2.5 py-1 text-xs font-semibold', tone === 'success' && 'bg-emerald-50 text-emerald-700', tone === 'warning' && 'bg-amber-50 text-amber-700', tone === 'neutral' && 'bg-slate-100 text-slate-600')}>{children}</span>; }
export function Input({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input className={cn('w-full rounded-lg border border-slate-200 bg-white py-2.5 pl-9 pr-3 text-sm outline-none transition placeholder:text-slate-400 focus:border-brand-500 focus:ring-2 focus:ring-brand-100', className)} {...props} /></div>; }
export function Select({ className, children, ...props }: SelectHTMLAttributes<HTMLSelectElement>) { return <div className="relative"><select className={cn('w-full appearance-none rounded-lg border border-slate-200 bg-white px-3 py-2.5 pr-9 text-sm text-slate-700 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100', className)} {...props}>{children}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /></div>; }
export function Table({ children }: { children: ReactNode }) { return <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm">{children}</table></div>; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-slate-200 bg-white px-6 py-20 text-center"><div className="mb-4 rounded-full bg-brand-50 p-3 text-brand-600"><Inbox className="size-6" /></div><h2 className="display-font text-lg font-bold text-ink">{title}</h2><p className="mt-2 max-w-md text-sm text-slate-500">{description}</p></div>; }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description: string; action?: ReactNode }) { return <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.18em] text-brand-600">{eyebrow ?? 'Espacio de trabajo'}</p><h1 className="display-font text-3xl font-extrabold tracking-tight text-ink sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm text-slate-500 sm:text-base">{description}</p></div>{action}</div>; }
export function Section({ title, action, children }: { title: string; action?: ReactNode; children: ReactNode }) { return <section><div className="mb-4 flex items-center justify-between"><h2 className="display-font text-lg font-bold text-ink">{title}</h2>{action}</div>{children}</section>; }
export function StatCard({ label, value, change, positive = true }: { label: string; value: string; change: string; positive?: boolean }) { return <Card className="p-5"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-3 display-font text-2xl font-extrabold tracking-tight text-ink">{value}</p><p className={cn('mt-3 text-xs font-bold', positive ? 'text-emerald-600' : 'text-rose-600')}>{change}<span className="ml-1 font-medium text-slate-400">vs. mes anterior</span></p></Card>; }
export function Skeleton({ className }: { className?: string }) { return <div className={cn('animate-pulse rounded-lg bg-slate-100', className)} />; }
export function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30 p-4 backdrop-blur-sm"><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl border border-slate-200 bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-4"><h2 className="display-font text-lg font-bold text-ink">{title}</h2><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X className="size-5" /></button></div><div className="p-6">{children}</div></div></div>; }
export function Toast({ message, tone = 'success', onClose }: { message: string; tone?: 'success' | 'error'; onClose: () => void }) { return <div role="status" className="fixed bottom-5 right-5 z-[60] flex max-w-sm items-center gap-3 rounded-xl border border-slate-200 bg-white px-4 py-3 shadow-2xl"><span className={tone === 'success' ? 'text-emerald-600' : 'text-rose-600'}>{tone === 'success' ? <CheckCircle2 className="size-5" /> : <AlertCircle className="size-5" />}</span><span className="text-sm font-medium text-slate-700">{message}</span><button className="ml-2 text-slate-400 hover:text-slate-700" onClick={onClose}><X className="size-4" /></button></div>; }
export function LoadingButton({ children, loading, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { loading?: boolean }) { return <Button disabled={loading || props.disabled} {...props}>{loading && <LoaderCircle className="size-4 animate-spin" />}{children}</Button>; }
